version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

hooks:
  AfterInstall:
    - location: scripts/configure_app.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
