#!/bin/bash

#sudo apt -y upgrade && sudo apt -y update
sudo yum install -y nodejs
sudo yum install -y npm
sudo yum install -y git
sudo yum install -y nginx

#Trying Hooks

npm -v
node -v
git -v

sudo git clone https://github.com/M-Amman-C/Tic-Tac-Toe.git

cd Tic-Tac-Toe/

ec2_public_ip=$(curl -s https://checkip.amazonaws.com)

npm install
sudo npm install pm2 -g
pm2 startup ubuntu
pm2 start index.js


sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF 
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;
	
	server_name http://\$ec2_public_ip/;

    	location / {
        	proxy_pass http://localhost:3000; #whatever port your app runs on
        	proxy_http_version 1.1;
        	proxy_set_header Upgrade \$http_upgrade;
        	proxy_set_header Connection 'upgrade';
        	proxy_set_header Host \$host;
        	proxy_cache_bypass \$http_upgrade;
    	}
}
EOF

sudo nginx -t

sudo nginx -s reload
